# Generated by Django 5.0.7 on 2024-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='non_academic',
        ),
        migrations.AlterField(
            model_name='department',
            name='academic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
